# Generated by Django 4.0.6 on 2022-07-09 13:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', unique=True, verbose_name='Телефон'),
        ),
    ]
